### ISSUE TITLE
invalid_client

### ISSUE THREAD

**Issue by knighti** [bshaffer/oauth2-server-php-docs#66] opened 2015-05-02 08:17 UTC
hello, i have followed the cookbook by every step. http://bshaffer.github.io/oauth2-server-php-docs/cookbook/

During [Create a Token Controller] when i give it i try to test the files it returns an error which is as follows:
{
"error": "invalid_client",
"error_description": "Client credentials were not found in the headers or body"
}

I have used hurl.it to test the http Authorization

I have also attached the images of the request
![request](https://cloud.githubusercontent.com/assets/12207616/7440433/42adb678-f0cd-11e4-9f52-24a601863d0f.PNG)
![request_1](https://cloud.githubusercontent.com/assets/12207616/7440432/42ad6740-f0cd-11e4-9493-d49e032bed4c.PNG)
![response](https://cloud.githubusercontent.com/assets/12207616/7440431/42acf2c4-f0cd-11e4-87d1-ccfed3a89420.PNG)

Kindly guide me through this.

**Comment by bshaffer** [comment] 2015-05-04 23:08
closing, as this is a duplicate of https://github.com/bshaffer/oauth2-server-php/issues/577

**Closed by bshaffer** 2015-05-04 23:08 UTC
