### ISSUE TITLE
Automatic Deletion of authorization code

### ISSUE THREAD

**Issue by timyounes** [bshaffer/oauth2-server-php-docs#92] opened 2017-01-18 01:35 UTC
Hi,

Why is it when i use Authorization Code Grant Type in one process only the generated authorization code in the oauth_authorization_codes table automatically deleted?

**Comment by bshaffer** [comment] 2017-01-18 02:52
Closing as a duplicate of https://github.com/bshaffer/oauth2-server-php/issues/798

**Closed by bshaffer** 2017-01-18 02:52 UTC
